name: crochet_maze
version: 0.2.1
author: Vitaliy Vostrikov <rasart.pro@gmail.com>
description: Crochet maze preview
homepage: 'https://github.com'
documentation: 'https://github.com'
environment:
  sdk: '>=1.22.1-dev <2.0.0'
dependencies:
  angular2: '^3.0.0-alpha+1'
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: '^0.12.20+3'
transformers:
  - angular2/transform/codegen
  - angular2:
      platform_directives:
        - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
        - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
  - test/pub_serve:
      $include: test/**_test.dart
  - $dart2js:
      commandLineOptions:
        - '--show-package-warnings'
  - dart_to_js_script_rewriter